import torch
import fairseq
# Tell PyTorch to trust the fairseq dictionary class when loading voice models
torch.serialization.add_safe_globals([fairseq.data.dictionary.Dictionary])

import io
import os
import tempfile
import soundfile as sf
from kokoro import KPipeline
from rvc_python.infer import RVCInference 

class SpongeTTS:
    def __init__(self):
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        
        # 1. Initialize local Kokoro baseline generator
        self.pipeline = KPipeline(lang_code='a', device=self.device)
        
        # 2. Initialize and configure the local RVC engine
        self.rvc = RVCInference(device=self.device)
        self.rvc.load_model("weights/model.pth") 
        
        # --- FIXED CARTOON TUNING PARAMETERS ---
        self.rvc.f0_up_key = 8             
        self.rvc.f0_method = "rmvpe"       
        self.rvc.file_index = "weights/model.index" 
        self.rvc.index_rate = 0.55         

    def get_speech(self, text: str) -> io.BytesIO:
        # Simple phonetic hotfix: Replace 'Juan' with an easily pronounceable phonetic text
        # string in standard lowercase so Kokoro reads it naturally as a whole word.
        #clean_text = text.replace("Juan", "wahn").replace("juan", "wahn")
        #print(f"Feeding clean text to engine: \"{clean_text}\"")
        
        # Segment via standard sentence limits and pass to Kokoro pipeline
        generator = self.pipeline(text, voice="am_adam", speed=1.3, split_pattern=r'[.!?\n]+')
        
        audio_segments = []
        for _, _, audio in generator:
            audio_segments.append(audio)
            
        if not audio_segments:
            raise ValueError("No baseline voice audio could be generated by Kokoro.")
            
        base_audio = torch.cat(audio_segments).numpy()
        
        # Use isolated temporary paths for multi-threading safety
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp_base, \
             tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp_sponge:
            base_path = tmp_base.name
            sponge_path = tmp_sponge.name

        try:
            sf.write(base_path, base_audio, 24000)
            
            if os.path.exists(base_path):
                self.rvc.infer_file(base_path, sponge_path)
            
            with open(sponge_path, "rb") as f:
                buffer = io.BytesIO(f.read())
                
        except Exception as conversion_error:
            print(f"RVC Processing Exception Caught: {conversion_error}")
            with open(base_path, "rb") as f:
                buffer = io.BytesIO(f.read())
                
        finally:
            if os.path.exists(base_path):
                try: os.remove(base_path)
                except Exception: pass
            if os.path.exists(sponge_path):
                try: os.remove(sponge_path)
                except Exception: pass
                
        buffer.seek(0)
        return buffer

# --- TEST ROUTINE BLOCK ---
if __name__ == "__main__":
    try:
        print("Initializing SpongeTTS pipeline...")
        tts = SpongeTTS()
        
        test_phrase = "Good morning Juan! I am completely offline, and it is time to make some krabby patties."
        print(f"\nTesting phrase: \"{test_phrase}\"")
        
        audio_buffer = tts.get_speech(test_phrase)
        
        output_filename = "test_spongebob.wav"
        with open(output_filename, "wb") as f:
            f.write(audio_buffer.getbuffer())
            
        print(f"\n🎉 Success! Play: {output_filename}")
        
    except Exception as e:
        print(f"\nAn error occurred during execution: {e}")
