import torch
import fairseq
# Tell PyTorch to trust the fairseq dictionary class when loading voice models
torch.serialization.add_safe_globals([fairseq.data.dictionary.Dictionary])

import io
import os
import re
import soundfile as sf
from kokoro import KPipeline
from rvc_python.infer import RVCInference 
import tempfile


class SpongeTTS:
    def __init__(self):
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        
        # 1. Initialize local Kokoro baseline generator
        self.pipeline = KPipeline(lang_code='a', device=self.device)
        
        # 2. Initialize and configure the local RVC engine
        self.rvc = RVCInference(device=self.device)
        self.rvc.load_model("weights/model.pth") 
        
        # --- CARTOON CHARACTER OPTIMIZATIONS ---
        self.rvc.f0_up_key = 13            # Shifts pitch up slightly higher than an octave (+13 semitones)
        self.rvc.f0_method = "rmvpe"       # Premium pitch tracking to follow expressive speech cleanly
        self.rvc.file_index = "weights/model.index" # Blends in SpongeBob's exact accent maps
        self.rvc.index_rate = 0.65         # Balance weight (0.6 - 0.7 gives optimal inflection variance)

    def _spongebobify_text(self, text: str) -> str:
        """
        Formats text to break the monotone delivery and patches pronunciation bugs.
        """
        processed = text.strip()
        
        # --- PHONETIC PRONUNCIATION DICTIONARY ---
        # Map words that the TTS engine mispronounces to their phonetic equivalents
        pronunciation_patches = {
            r"\bJuan\b": "Wahn",     # Forces "Juan" to be pronounced properly as "Wahn"
            r"\bjuan\b": "Wahn",
            # You can add other custom names or words here as you run into them:
            # r"\bFastAPI\b": "Fast A P I",
        }
        
        # Apply the phonetic patches using regex word boundaries
        for pattern, replacement in pronunciation_patches.items():
            processed = re.sub(pattern, replacement, processed)
        
        # Clean up punctuation and apply upper-case shouting for energy
        processed = processed.replace(".", "!")
        processed = processed.upper()
        
        if not processed.endswith("!"):
            processed += "!"
            
        return processed


    def get_speech(self, text: str) -> io.BytesIO:
        # 1. Standardize and transform text structure
        animated_text = self._spongebobify_text(text)
        
        # 2. FIXED: Use Kokoro's native sentence-splitting pattern execution block.
        # This keeps audio tensors small and clean, preventing RVC frame size mismatches.
        generator = self.pipeline(animated_text, voice="am_adam", speed=1.3, split_pattern=r'[.!?\n]+')
        
        audio_segments = []
        for _, _, audio in generator:
            audio_segments.append(audio)
            
        if not audio_segments:
            raise ValueError("No baseline voice audio could be generated by Kokoro.")
            
        # Join all the small, clean sentence audio chunks together safely
        base_audio = torch.cat(audio_segments).numpy()
        
        # 3. Create unique temp paths for this thread request cycle
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp_base, \
             tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp_sponge:
            base_path = tmp_base.name
            sponge_path = tmp_sponge.name

        try:
            # Write out baseline tracking track
            sf.write(base_path, base_audio, 24000)
            
            # Check if paths exist and execute conversion safely
            if os.path.exists(base_path):
                self.rvc.infer_file(base_path, sponge_path)
            
            # Read converted audio file buffer contents straight back into memory
            with open(sponge_path, "rb") as f:
                buffer = io.BytesIO(f.read())
                
        except Exception as conversion_error:
            print(f"RVC Processing Exception Caught: {conversion_error}")
            # Safe runtime fallback: Stream raw baseline audio if RVC encounters a calculation block
            with open(base_path, "rb") as f:
                buffer = io.BytesIO(f.read())
                
        finally:
            # Strict file cleanup handling loops so storage never fills up on Linux
            if os.path.exists(base_path):
                try: os.remove(base_path)
                except Exception: pass
            if os.path.exists(sponge_path):
                try: os.remove(sponge_path)
                except Exception: pass
                
        buffer.seek(0)
        return buffer


# --- TEST ROUTINE BLOCK ---
if __name__ == "__main__":
    try:
        print("Initializing Optimized SpongeTTS pipeline...")
        tts = SpongeTTS()
        
        # Test input string - notice it's standard, but the internal formatter will hype it up!
        test_phrase = input("Spongebob: ")
        print(f"\nIncoming text stream: \"{test_phrase}\"")
        
        # Generate the audio stream buffer
        audio_buffer = tts.get_speech(test_phrase)
        
        # Save the buffer stream contents locally to a permanent WAV file
        output_filename = "test_spongebob.wav"
        with open(output_filename, "wb") as f:
            f.write(audio_buffer.getbuffer())
            
        print(f"\n🎉 Success! Open your directory and play: {output_filename}")
        
    except Exception as e:
        print(f"\nAn error occurred during execution: {e}")
        
    finally:
        # Clean up temporary disk files used by the inference engine loop
        for temp_file in ["temp_base.wav", "temp_spongebob.wav"]:
            if os.path.exists(temp_file):
                try:
                    os.remove(temp_file)
                except Exception:
                    pass
